package edu.uiowa.icts.bluebutton.dao;

/*
 * #%L
 * blue-button Spring MVC Web App
 * %%
 * Copyright (C) 2014 - 2015 University of Iowa Institute for Clinical and Translational Science (ICTS)
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

import edu.uiowa.icts.bluebutton.domain.LabTest;
import edu.uiowa.icts.bluebutton.domain.LabTestRange;
import edu.uiowa.icts.spring.*;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.web.WebAppConfiguration;

/**
 * Unit test Template
 * Generated by Protogen
 * @since 10/29/2014 09:18:02 CDT
 */
@WebAppConfiguration
public class LabTestRangeTest extends AbstractSpringTestCase {

    @Autowired
    private BluebuttonDaoService bluebuttonDaoService;

    public BluebuttonDaoService getBluebuttonDaoService() {
        return bluebuttonDaoService;
    }


    @Test
    public void testServiceName() {
    	assertEquals( true, true );
    }

    @Before
    public void setUp() throws Exception {
    	super.setUp();
    }

    @After
    public void tearDown() throws Exception {
    	super.tearDown();
    }
    
    @Test
    public void testCSVImport() throws IOException {
    	// import parent objects
    	assertEquals( 0, this.getBluebuttonDaoService().getLabTestService().count() );
    	
    	File file1 = new File("src/test/resources/csv/lab-tests.csv");
		this.getBluebuttonDaoService().getLabTestService().importCSV(new FileInputStream(file1));
		
    	assertEquals( 11, this.getBluebuttonDaoService().getLabTestService().count() );
    	
    	// now test child object import
    	assertEquals( 0, this.getBluebuttonDaoService().getLabTestRangeService().count() );
    	
    	File file = new File("src/test/resources/csv/lab-test-ranges.csv");
		this.getBluebuttonDaoService().getLabTestRangeService().importCSV(new FileInputStream(file));
				
    	assertEquals( 30, this.getBluebuttonDaoService().getLabTestRangeService().count() );
    	
    	LabTestRange labTestRange = this.getBluebuttonDaoService().getLabTestRangeService().findById(1);
    	assertEquals(new Integer(1), labTestRange.getLabTest().getLabTestId());
    	assertEquals("FM", labTestRange.getSex());
    	assertEquals(0.0, labTestRange.getMinAgeYears());
    	assertEquals(127.0,labTestRange.getMaxAgeYears());
    	assertEquals(0.0,labTestRange.getMinNormal());
    	assertEquals(0.0,labTestRange.getMaxNormal());
    	
    	LabTestRange labTestRange15 = this.getBluebuttonDaoService().getLabTestRangeService().findById(15);
    	assertEquals(new Integer(25), labTestRange15.getLabTest().getLabTestId());
    	assertEquals("FM", labTestRange15.getSex());
    	assertEquals(0.0, labTestRange15.getMinAgeYears());
    	assertEquals(127.0,labTestRange15.getMaxAgeYears());
    	assertEquals(1.200000048,labTestRange15.getMinNormal());
    	assertEquals(2.599999905,labTestRange15.getMaxNormal());


    	// confirm that parent-child relationships were established
    	LabTest labTest = this.getBluebuttonDaoService().getLabTestService().findById(1);
    	assertEquals(1,labTest.getLabTestRanges().size());
    	
    	LabTest labTest43 = this.getBluebuttonDaoService().getLabTestService().findById(43);
    	assertEquals(12,labTest43.getLabTestRanges().size());
    }

}