package edu.uiowa.icts.bluebutton.dao;

/*
 * #%L
 * blue-button Spring MVC Web App
 * %%
 * Copyright (C) 2014 - 2015 University of Iowa Institute for Clinical and Translational Science (ICTS)
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.web.WebAppConfiguration;

import edu.uiowa.icts.spring.AbstractSpringTestCase;

/**
 * Generated by Protogen
 * Unit test Template
 * Wed Jul 30 14:56:41 CDT 2014
 */

@WebAppConfiguration
public class PersonTest extends AbstractSpringTestCase {


    @Autowired
    private BluebuttonDaoService daoService;

    @Test
    public void testServiceName() {
    	assertEquals(true,true);
    	       
    }
    	   
    @Before
    public void setUp() throws Exception {
    	super.setUp();
    		   
    }
    	   
    @After
    public void tearDown() throws Exception {
    	super.tearDown();
    }

}
