package edu.uiowa.icts.bluebutton.resource;

/*
 * #%L
 * blue-button Spring MVC Web App
 * %%
 * Copyright (C) 2014 - 2015 University of Iowa Institute for Clinical and Translational Science (ICTS)
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import java.util.List;

import org.hamcrest.core.IsNull;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Arrays;

import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.datatable.DataTableSearch;
import edu.uiowa.icts.bluebutton.dao.*;
import edu.uiowa.icts.bluebutton.domain.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;
import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import edu.uiowa.icts.bluebutton.controller.AbstractControllerMVCTests;

/**
 * Generated by Protogen
 * @since Wed Jul 08 08:12:43 CDT 2015
 */
@WithMockUser(username="user", roles={"BLUEBUTTON_ADMIN"})
public class LabResultSynonymResourceMvcTest extends AbstractControllerMVCTests {
	
    private LabResultSynonym firstLabResultSynonym;
    private ObjectMapper mapper;
    
    @Before
    public void before() { 
        // add 20 records to test database
        for(int x=1; x<21; x++){
        	LabResultSynonym labResultSynonym = new LabResultSynonym();
        	labResultSynonym.setOfficialName("lab result " + x);
        	labResultSynonym.setUnofficialName("lab unoffical name " + x);
        	bluebuttonDaoService.getLabResultSynonymService().save(labResultSynonym);
	        if (x == 1){
	        	// use this ID for update, show, and delete assertions
	        	firstLabResultSynonym = labResultSynonym;
	        }
        }   
        this.mapper = new ObjectMapper();
        // fix NonUniqueObjectException
        this.bluebuttonDaoService.getLabResultSynonymService().getSession().flush();
        this.bluebuttonDaoService.getLabResultSynonymService().getSession().clear();
    }    
      
    @Test
    public void getByPathVariableIdShouldLoadAndReturnObject() throws Exception {
    	mockMvc.perform(get("/api/labresultsynonym/"+firstLabResultSynonym.getLabResultSynonymId().toString()))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
        .andExpect(jsonPath("$.labResultSynonymId", is(firstLabResultSynonym.getLabResultSynonymId())))
        ;
    }
  
    @Test
    public void getByPathVariableIdShouldReturn404ForBogusId() throws Exception {
    	mockMvc.perform(get("/api/labresultsynonym/-123")).andExpect(status().isNotFound()).andExpect(jsonPath("$.message", is("/api/labresultsynonym/-123 could not be found.")));
    }
    
    @Test
    public void restMappingNotFoundShouldReturn404() throws Exception {
    	mockMvc.perform(get("/api/labresultsynonym/asdfasdf/asdfasdf"))
    	.andExpect(status().isNotFound())
    	 .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
        .andExpect(jsonPath("$.message", is("/api/labresultsynonym/asdfasdf/asdfasdf could not be found.")))
    	;
    }
    
    @Test
    public void createShouldPersistAndReturnObject() throws Exception {
	   long count = bluebuttonDaoService.getLabResultSynonymService().count();	       
	   LabResultSynonym labResultSynonym = new LabResultSynonym(); 
	   labResultSynonym.setOfficialName("test");
	   labResultSynonym.setUnofficialName("good test");
	   
       mockMvc.perform(post("/api/labresultsynonym/").content(this.mapper.writeValueAsString(labResultSynonym))
	   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON))
       .andExpect(status().isOk())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.labResultSynonymId").value(IsNull.notNullValue()))  
       ;
       
       assertEquals("count should increase by 1", count +1 , bluebuttonDaoService.getLabResultSynonymService().count());
	}
     
    @Test
    public void updateShouldPersistExistingAndReturnObject() throws Exception {
       long count = bluebuttonDaoService.getLabResultSynonymService().count();

       mockMvc.perform(post("/api/labresultsynonym/"+ firstLabResultSynonym.getLabResultSynonymId().toString())
    		   .content(this.mapper.writeValueAsString(firstLabResultSynonym))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON))
       .andExpect(status().isOk())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.labResultSynonymId", is(firstLabResultSynonym.getLabResultSynonymId())))
       ;
         
       assertEquals("count NOT should increase", count , bluebuttonDaoService.getLabResultSynonymService().count());
  	}  
    
    @Test
    public void updateByPathVariableIdShouldReturn404ForMismatchBetweenPathIdAndObjectId() throws Exception {	       
       String correctId =  firstLabResultSynonym.getLabResultSynonymId().toString();
       // this ID manipulation should be overwritten with path variable id
       firstLabResultSynonym.setLabResultSynonymId(-123);
       
       mockMvc.perform(post("/api/labresultsynonym/"+correctId)
    		   .content(this.mapper.writeValueAsString(firstLabResultSynonym))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON))
       .andExpect(status().isNotFound())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.message", is("/api/labresultsynonym/" +correctId +" could not be found.")))
       ;
  	} 
    
    @Test
    public void updateByPathVariableIdShouldReturn404ForBogusPathId() throws Exception {
    	mockMvc.perform(post("/api/labresultsynonym/-123")
    			.content(this.mapper.writeValueAsString(firstLabResultSynonym))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON))
    	.andExpect(status().isNotFound())
    	.andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	    .andExpect(jsonPath("$.message", is("/api/labresultsynonym/-123 could not be found.")));
    }
    
    @Test
    public void deleteShouldDeleteAndReturnStatusOk() throws Exception {
        long count = bluebuttonDaoService.getLabResultSynonymService().count();

        mockMvc.perform(delete("/api/labresultsynonym/"+ firstLabResultSynonym.getLabResultSynonymId().toString()))
       .andExpect(status().isOk());  
       
       assertEquals("count should decrease by 1", count - 1 , bluebuttonDaoService.getLabResultSynonymService().count());
    }
    
    @Test
    public void deleteShouldFailWithBogusId() throws Exception {
        long count = bluebuttonDaoService.getLabResultSynonymService().count();

        mockMvc.perform(delete("/api/labresultsynonym/-123"))
       .andExpect(status().isNotFound())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.message", is("/api/labresultsynonym/-123 could not be found.")));  
       
       assertEquals("count should NOT decrease by 1", count , bluebuttonDaoService.getLabResultSynonymService().count());
    }

    @Test
    public void listShouldReturnAllByDefault() throws Exception {
    	mockMvc.perform(get("/api/labresultsynonym/"))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
         .andExpect(jsonPath("$.", hasSize(is(20))))
        .andExpect(jsonPath("$.[0].labResultSynonymId", is(firstLabResultSynonym.getLabResultSynonymId())))
        ;
    }
    
    @Test
    public void listShouldReturnAllByDefaultWithoutTrailUrlSlash() throws Exception {
    	mockMvc.perform(get("/api/labresultsynonym"))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
         .andExpect(jsonPath("$.", hasSize(is(20))))
        .andExpect(jsonPath("$.[0].labResultSynonymId", is(firstLabResultSynonym.getLabResultSynonymId())))
        ;
    }
}