package edu.uiowa.icts.bluebutton.controller;

/*
 * #%L
 * blue-button Spring MVC Web App
 * %%
 * Copyright (C) 2014 - 2015 University of Iowa Institute for Clinical and Translational Science (ICTS)
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import edu.uiowa.icts.bluebutton.domain.ClinicalDocument;


/**
 * Generated by Protogen 
 * @since 07/31/2014 09:37:03 CDT
 */
@RestController
@RequestMapping( "/monitor/*" )
public class MonitorController extends AbstractBluebuttonController {

    private static final Log log = LogFactory.getLog( MonitorController.class );

	@RequestMapping( value = { "", "/" } , method = RequestMethod.GET )
	public String index() {
		try {
			List<ClinicalDocument> list = bluebuttonDaoService.getClinicalDocumentService().list();
			if (list.size() > 0){
				return "SUCCESS";
			} else {
				log.error( "Failed: no Clinical Documents found in the database.");
				return "Failed: no Clinical Documents found in the database.";
			}
		} catch (Exception e){
			log.error( "Error: ", e );
			return "Failed: " + e.getMessage();
		}
	}
}