package edu.uiowa.icts.bluebutton.dao;

/*
 * #%L
 * blue-button Spring MVC Web App
 * %%
 * Copyright (C) 2014 - 2015 University of Iowa Institute for Clinical and Translational Science (ICTS)
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Generated by Protogen
 * @since 10/29/2014 09:18:02 CDT
 */
@Component
public class BluebuttonDaoService {

	private LabResultSynonymService synonymSearchService;

    /*********** personService ****************/
    private PersonService personService;

    public PersonService getPersonService() {
        return personService;
    }

    @Autowired
    public void setPersonService( PersonService personService ) {
        this.personService = personService;
    }




  








    /*********** clinicalDocumentService ****************/
    private ClinicalDocumentService clinicalDocumentService;

    public ClinicalDocumentService getClinicalDocumentService() {
        return clinicalDocumentService;
    }

    @Autowired
    public void setClinicalDocumentService( ClinicalDocumentService clinicalDocumentService ) {
        this.clinicalDocumentService = clinicalDocumentService;
    }


    /*********** labTestService ****************/
    private LabTestService labTestService;

    public LabTestService getLabTestService() {
        return labTestService;
    }

    @Autowired
    public void setLabTestService( LabTestService labTestService ) {
        this.labTestService = labTestService;
    }



    /*********** labTestRangeService ****************/
    private LabTestRangeService labTestRangeService;

    public LabTestRangeService getLabTestRangeService() {
        return labTestRangeService;
    }

    @Autowired
    public void setLabTestRangeService( LabTestRangeService labTestRangeService ) {
        this.labTestRangeService = labTestRangeService;
    }


    @Autowired
    private LoincCodeCategoryService loincCodeCategoryService;

    public LoincCodeCategoryService getLoincCodeCategoryService() {
        return loincCodeCategoryService;
    }

    
	public LabResultSynonymService getLabResultSynonymService() {
		return synonymSearchService;
	}

	@Autowired
	public void setLabResultSynonymService(LabResultSynonymService synonymSearchService) {
		this.synonymSearchService = synonymSearchService;
	}

    
}
