package edu.uiowa.icts.bluebutton.dao;

/*
 * #%L
 * blue-button Spring MVC Web App
 * %%
 * Copyright (C) 2014 - 2015 University of Iowa Institute for Clinical and Translational Science (ICTS)
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import edu.uiowa.icts.spring.*;
import edu.uiowa.icts.bluebutton.domain.*;
import edu.uiowa.icts.bluebutton.json.LoincCode;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import org.json.JSONObject;

import edu.uiowa.icts.util.SortColumn;

/**
 * Generated by Protogen 
 * @since 01/27/2015 10:53:12 CST
 */
public interface LoincCodeCategoryService extends GenericDaoInterface<LoincCodeCategory> {

    public LoincCodeCategory findById( Integer id );

	public void importCSV(InputStream fileInputStream) throws IOException ;

	public List<LoincCode> findByLoincCodes(String string);

}