package edu.uiowa.icts.bluebutton.controller;

/*
 * #%L
 * blue-button Spring MVC Web App
 * %%
 * Copyright (C) 2014 - 2015 University of Iowa Institute for Clinical and Translational Science (ICTS)
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import static org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers.springSecurity;

import java.io.FileNotFoundException;
import java.io.IOException;

import org.junit.Before;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.web.FilterChainProxy;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.WebApplicationContext;

import edu.uiowa.icts.bluebutton.dao.BluebuttonDaoService;
import edu.uiowa.icts.bluebutton.dao.ClinicalDocumentService;
import edu.uiowa.icts.bluebutton.dao.PersonService;

/**
 * Generated by Protogen
 * @since Fri Aug 01 10:04:19 CDT 2014
 */
@WebAppConfiguration
@ContextConfiguration({
	"classpath:spring/dispatcher-servlet.xml"
})
@Transactional
@RunWith(SpringJUnit4ClassRunner.class)
public abstract class AbstractControllerMVCTests {
	
	@Autowired
    protected BluebuttonDaoService bluebuttonDaoService; 
	
	@Autowired
	protected PersonService personService;
	
	@Autowired
	protected ClinicalDocumentService clinicalDocumentService;
	
	protected MockMvc mockMvc;

	@Autowired
	protected WebApplicationContext wac;

	@Before
	public void setup() throws FileNotFoundException, IOException {
		this.mockMvc = MockMvcBuilders.webAppContextSetup(this.wac).apply(springSecurity()).build();

	}

} 